sudo:	required
services:
  - docker

before_install:
  - docker build -t urmel80/multi-docker -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true urmel80/multi-docker npm test 

after_success:
  - docker build -t urmel80/multi-client ./client
  - docker build -t urmel80/multi-nginx ./nginx
  - docker build -t urmel80/multi-server ./server
  - docker build -t urmel80/multi-worker ./worker

# Log into the docker client
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin 

# Take those images and push them to docker hub
  - docker push urmel80/multi-client
  - docker push urmel80/multi-nginx
  - docker push urmel80/multi-server
  - docker push urmel80/multi-worker

# Deploy to AWS
deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-east-1-016154154267'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY